import type { TokenRotationManager } from './types';

/**
 * Client-side token rotation manager.
 *
 * The backend issues batches of BLE tokens. This manager cycles through them
 * at the configured rotation interval, updating the BLE advertiser with each
 * new token. When tokens run low, it fires a callback so the client can
 * request a new batch.
 *
 * Architecture note: tokens are pre-generated by the backend so the server
 * can later map observed tokens back to specific users and time windows.
 * The client never generates its own tokens.
 */
export class ClientTokenRotationManager implements TokenRotationManager {
  private tokens: string[] = [];
  private currentIndex = -1;
  private intervalId: ReturnType<typeof setInterval> | null = null;
  private lowCallback: ((remaining: number) => void) | null = null;
  private readonly LOW_TOKEN_THRESHOLD = 3;

  start(tokens: string[], rotationIntervalMs: number): void {
    this.stop();
    this.tokens = [...tokens];
    this.currentIndex = 0;

    this.intervalId = setInterval(() => {
      this.currentIndex++;

      if (this.currentIndex >= this.tokens.length) {
        // Out of tokens — stop rotation; the low-token callback should have
        // already triggered a refetch
        this.stop();
        return;
      }

      const remaining = this.tokens.length - this.currentIndex - 1;
      if (remaining <= this.LOW_TOKEN_THRESHOLD && this.lowCallback) {
        this.lowCallback(remaining);
      }
    }, rotationIntervalMs);
  }

  stop(): void {
    if (this.intervalId !== null) {
      clearInterval(this.intervalId);
      this.intervalId = null;
    }
  }

  getCurrentToken(): string | null {
    if (this.currentIndex < 0 || this.currentIndex >= this.tokens.length) {
      return null;
    }
    return this.tokens[this.currentIndex];
  }

  remainingTokens(): number {
    if (this.currentIndex < 0) return 0;
    return Math.max(0, this.tokens.length - this.currentIndex - 1);
  }

  onTokensLow(callback: (remaining: number) => void): void {
    this.lowCallback = callback;
  }
}
